Added an automatic detector for a WAD's associated README / Text File
Spectere/Wadinator pull request #1
Opened 2022-10-28 08:27 UTC by 0xFC963F18DC21

## What

Added the ability for the Wadinator to detect a WAD's matching text file. Currently limited to text files that match their WAD's name in all but extension. For example: `gd.wad` and `gd.txt` match, but `some.wad` and `something.txt` does not.

- Can be configured to either print a command line to open an editor in read-only mode with the text file open, or to print out the whole contents of the text file in console.
- Editors can be configured fully in `Wadinator.toml`.

## Why

It seemed like a nice convenience feature that matches the suggested game command line feature to remove some manual work from the user when looking for readmes / text files associated with a WAD picked by the Wadinator, especially in very populated WAD directories.

2022-10-28 12:29 UTC, 0xFC963F18DC21 commented
Might attempt to deal with text files living in a separate directory before this is completely ready though.

2022-10-28 13:25 UTC, Spectere commented
Holy crap, this is awesome. This is actually the last feature I wanted to implement before the next tagged release (either 1.2.0 or 2.0.0…probably the latter). Thanks! :D

If you could have it recursively search directories, that would be immensely helpful for my use case. I primarily use this to randomly play D!ZONE WADs, and in the earlier editions of the disc they have this sort of structure:

```
MYWAD.WAD
TXT/MYWAD/MYWAD.TXT
```

Sometimes they'll even use the following (slightly more maddening) pattern:

```
MYWAD.WAD
TXT/MYWAD/MINE.TXT
```

I dumped the LEVELS directory from the DOS version of the discs and put them here if you want to see some practical examples: https://files.spectere.net/doom/

No worries if this is a bit outside of your intended scope. I can always extend upon your work if your needs have already been met. You've already been a great help. :)

2022-10-28 13:46 UTC, 0xFC963F18DC21 commented
Hm, would something like that be better as a flag (like `-dzone`) or a fully-fledged configuration option?

It shouldn't be too far out the scope to add something like this.

2022-10-28 14:31 UTC, Spectere commented
I envisioned it as a configuration option due to my use case (creating YouTube videos featuring the "best" WADs ever made). I made enough silly typos using the current build that ideally I'd like to just call the binary and have it do everything for me, haha.

Given the slapdash way these compilations were put together, this seems like the best approach to me, if directory search is enabled:

1. Do a recursive search for a text file sharing the WAD's name (since sometimes the TXT/* name is wrong, but the text file inside shares the WAD's name).
2. Do a recursive search for a directory sharing the WAD's base name and return a TXT file inside that directory. FILE_ID.DIZ should be ignored, as those files are largely useless in D!ZONE.

Just some of that fun DOS-era jankiness.

2022-10-28 16:50 UTC, Spectere commented
Awesome! I'll take a closer look when I get off work. Thanks again for all your help!

2022-10-29 02:14 UTC, Spectere requested changes
I should have been more clear on what I meant by "MINE.TXT." Sorry about that!

Other than that, this looks (and runs) great!

2022-10-29 02:14 UTC, Spectere commented on Wadinator/Program.cs
> +                "MINE.TXT",
Sorry, I should have been more clear about this one. :sweat_smile:

I meant to imply that on some occasions the text filename differs from the WAD file. It could be basically anything with a .TXT extension, as long as the directory name matches. So, `MYWAD.WAD`'s text file might be `TXT/MYWAD/MINE.TXT`, while `SUPERWAD.WAD`'s text file might be `TXT/SUPERWAD/BLAH.TXT`. The way they did it is pretty arbitrary.

2022-10-29 02:14 UTC, Spectere commented on Wadinator/Wadinator.toml
> +# - In [WADDIR]/TXT/[WADNAME]/MINE.TXT.
See other comment.

2022-10-29 05:12 UTC, 0xFC963F18DC21 commented on Wadinator/Program.cs
> +                "MINE.TXT",
Ah, never change, 90s compilation disks.

2022-10-29 05:45 UTC, 0xFC963F18DC21 commented
Alright, that should be that pattern tweaked to match any text file in the matching directory.

2022-10-29 08:52 UTC, merged

2022-10-29 08:55 UTC, Spectere commented
Looking good! Thanks again for your help. :)

As far as edge cases are concerned, it wouldn't surprise me if a few popped up. Pretty much the whole D!Zone series is one giant edge case, haha. At least modern stuff tends to be a bit more sane.

Before I close this PR: how would you like me to credit you?

2022-10-29 11:30 UTC, 0xFC963F18DC21 commented
> Before I close this PR: how would you like me to credit you?

Honestly, I haven't a clue. This is my first PR to a repository that isn't something I'm doing for university or something like that.

2022-10-31 23:24 UTC, Spectere commented
No worries! I just used your GitHub username for now. If you would prefer something else down the road, feel free to modify CREDITS.md and open a pull request. :)